ci:update release workflows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,21 +3,132 @@ name: Release
 on:
   push:
     branches:
-      - develop
+      - main
+  repository_dispatch:
+    types: [semantic-release]
+
+env:
+  THIRD_PARTY_GIT_AUTHOR_EMAIL: opensource+repolinter-action@newrelic.com
+  THIRD_PARTY_GIT_AUTHOR_NAME: Actionbot
+
 jobs:
-  release:
-    name: release
+  job-checkout-and-build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
+      - name: Checkout repo
         uses: actions/checkout@v2
 
-      - name: Semantic Release
-        uses: cycjimmy/semantic-release-action@v2
-        id: semantic
+      - name: Setup Node.js
+        uses: actions/setup-node@v1
         with:
-          extra_plugins: |
-            @semantic-release/git
-            @semantic-release/changelog
+          node-version: 12
+
+      - name: Cache node_modules
+        id: cache-node-modules
+        uses: actions/cache@v1
+        env:
+          cache-name: node-modules
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.cache-name }}-
+      - name: Install Dependencies
+        run: npm ci
+      
+      - name: Build and Test
+        run: npm run test
+  
+  job-generate-third-party-notices:
+    runs-on: ubuntu-latest
+    needs: job-checkout-and-build
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+
+      # Probably not necessary since the ubuntu-latest image would have latest Node LTS release
+      # and nothing in this job _needs_ older Node
+      - name: Setup Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12.x
+
+      - name: Download Cached Deps
+        id: cache-node-modules
+        uses: actions/cache@v1
+        env:
+          cache-name: node-modules
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.cache-name }}-
+      
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Install OSS CLI
+        run: |
+          sudo npm install -g @newrelic/newrelic-oss-cli
+      
+      - name: Generate Third Party Notices
+        run: |
+          if [ ! -f "third_party_manifest.json" ]; then
+            echo "::error::third_party_manifest.json is missing. Must generate using the newrelic-oss-cli."
+            exit 1
+          fi
+          # latest commit
+          LATEST_COMMIT=$(git rev-parse HEAD)
+          # latest commit where package.json was changed
+          LAST_CHANGED_COMMIT=$(git log -1 --format=format:%H --full-diff package.json)
+          if [ $LAST_CHANGED_COMMIT = $LATEST_COMMIT ]; then
+            git config user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
+            git config user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
+            oss third-party manifest
+            oss third-party notices
+            git add third_party_manifest.json
+            git add THIRD_PARTY_NOTICES.md
+            
+            git commit -m 'chore: update third-party manifest and notices [skip ci]'
+            git push origin ${GITHUB_REF#/refs/heads/} 
+          else
+            echo "No change in package.json, not regenerating third-party notices"
+          fi
+
+  job-generate-release:
+    runs-on: ubuntu-latest
+    needs: [job-checkout-and-build, job-generate-third-party-notices]
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          ref: master
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12.x
+      
+      - name: Download Cached Deps
+        id: cache-node-modules
+        uses: actions/cache@v1
+        env:
+          cache-name: node-modules
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.cache-name }}-
+      - name: Install Dependencies
+        run: npm ci
+      
+      - name: Build
+        run: npm run build
+
+      - name: Package
+        run: npm run package
+
+      - name: Run semantic-release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: npx semantic-release
